### ISSUE TITLE
运行命令显示却找不到模块

### ISSUE THREAD

**Issue by neko886** [valkjsaaa/danmaku_tools#5]
作者您好！
不知道为什么我这一样运行不了这个，看显示应该是安装成功了的
![QQ截图20220425093240](https://user-images.githubusercontent.com/103251269/165009000-53e76c24-bbe5-436f-bee5-e6e890557d23.jpg)

![QQ截图20220425093252](https://user-images.githubusercontent.com/103251269/165008998-484dd263-1903-4f84-ae71-725cf256f687.jpg)
试了好几次都不成功
![QQ截图20220425094123](https://user-images.githubusercontent.com/103251269/165008991-4a7d50d2-4fd0-45b0-b580-1e95450d445c.jpg)

**Comment by valkjsaaa** [comment]
这种情况一般是你的 pip3 和 python3 是不同的版本，把以下命令的输出贴过来看看？
`which python3` 和 `which pip3`

一般这样安装即可保证使用 `python3` 所对应的 `pip` 安装这个库：
`python3 -m pip install danmaku_tools`
